proposal filter changes
open-ic/open-chat pull request #3257
Opened 2023-03-01 18:05 UTC by julianjelfs

2023-03-01 18:13 UTC, megrogan approved these changes

2023-03-01 18:14 UTC, megrogan reviewed
Needs translations

2023-03-01 18:14 UTC, megrogan requested changes
Needs translations

2023-03-02 08:07 UTC, hpeebles commented on frontend/app/src/i18n/en.json
> +        "notificationsAction": "Notifications Actions",
Should be 'Notifications Index Actions'

2023-03-02 09:17 UTC, megrogan commented on frontend/app/src/i18n/cn.json
> +        "notificationsAction": "通知索引操作"
Ideally the key would change too but no biggy.

2023-03-02 10:51 UTC, hpeebles commented on frontend/app/src/i18n/es.json
> +        "notificationsAction": "Índice de notificaciones Acciones"
I know zero Spanish... but this one doesn't fit the same pattern...

2023-03-02 10:52 UTC, hpeebles commented on frontend/app/src/i18n/it.json
> +        "cyclesDispenserAction": "Cicli Azioni Dispenser",
This says 'Cycles Actions Dispenser'

2023-03-02 11:35 UTC, merged